import streamlit as st
import pandas as pd
import altair as alt
import json
import tls_client
from fetch_news import NewsExtractor
from openai import AsyncOpenAI
import asyncio
from classifier import NewsClassifier
from config import SYSTEM_PROMPT, JSON_SCHEMA, MAX_SNIPPET_LEN, HEADERS, KEYWORDS


session = tls_client.Session(
    client_identifier="chrome_120",
    random_tls_extension_order=True,
)

extractor = NewsExtractor(
    snippet_len=MAX_SNIPPET_LEN,
    header=HEADERS,
    keywords=KEYWORDS,
    session=session
)

articles = extractor.fetch_all()

client = AsyncOpenAI()

classifier = NewsClassifier(
    client=client,
    json_schema=JSON_SCHEMA,
    prompt=SYSTEM_PROMPT,
    articles=articles,
    model="gpt-5-mini",
)

result = asyncio.run(classifier.main(batch_size=25, max_parallel=6))

st.set_page_config(page_title="Regulatory Intelligence", page_icon="📰", layout="wide")
st.markdown(
    """
    <style>
    .stApp {
        background-color: #ffffff;
    }
    [data-testid="stAppViewContainer"] {
        background: #ffffff;
    }
    [data-testid="stHeader"] {
        background: transparent;
    }
    [data-testid="stSidebar"] {
        background: #ffffff;
    }
    /* lighten the input controls */
    .stTextInput > div > div > input,
    .stSelectbox > div > div {
        background: #ffffff !important;
        color: #0f172a !important;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
    }
    .stMultiSelect > div {
        background: #ffffff !important;
        color: #0f172a !important;
        border: 1px solid #e2e8f0 !important;
        border-radius: 10px !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)



flat_articles = []
for region, items in result.items():
    for art in items:
        copy = art.copy()
        copy["region"] = region
        flat_articles.append(copy)


def get_sentiment(article):
    s = (article.get("nbimSentiment") or "").lower().strip()
    if s in {"bullish", "bearish", "neutral"}:
        return s
    return "neutral"


def sentiment_color(sentiment: str):
    palette = {
        "bullish": "#31c47e",  
        "neutral": "#9aa4b5",  
        "bearish": "#e45b5b", 
    }
    return palette.get(sentiment, "#9aa4b5")
    



st.markdown(
    """
    <div style="display:flex; align-items:center; gap:12px;">
        <div style="width:44px; height:44px; border-radius:12px; background:#f5b63f; display:flex; align-items:center; justify-content:center; font-size:24px;">📰</div>
        <div>
            <div style="font-size:26px; font-weight:700; color:#0f172a;">Regulatory News NBIM</div>
            <div style="color:#475569;"> Regulatory news relevant to NBIM's five biggest markets generated by ChatGPT</div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

st.divider()


sentiment_counts = {}
for region, items in result.items():
    sentiment_counts[region] = {"bullish": 0, "neutral": 0, "bearish": 0}
    for a in items:
        sentiment_counts[region][get_sentiment(a)] += 1

df_sent = (
    pd.DataFrame.from_dict(sentiment_counts, orient="index")
    .reset_index(names="Region")
    .melt(id_vars="Region", var_name="Sentiment", value_name="Count")
)

chart = (
    alt.Chart(df_sent)
    .mark_bar()
    .encode(
        x=alt.X("Region:N", sort=list(result.keys())),
        xOffset="Sentiment",
        y=alt.Y("Count:Q", title="Articles"),
        color=alt.Color(
            "Sentiment:N",
            scale=alt.Scale(
                domain=["bearish", "neutral", "bullish"],
                range=["#e45b5b", "#9aa4b5", "#31c47e"],
            ),
        ),
        tooltip=["Region", "Sentiment", "Count"],
    )
    .properties(height=320, title="Sentiment Analysis by Region", background="#ffffff")
    .configure_view(stroke="#e2e8f0", fill="#ffffff")
    .configure_axis(domainColor="#e2e8f0", tickColor="#e2e8f0", labelColor="#475569", titleColor="#0f172a")
    .configure_legend(
        labelColor="#475569",
        titleColor="#475569",
        orient="right",
        title=None,
        padding=8,
        labelFontSize=12,
    )
)

st.altair_chart(chart, use_container_width=True)


st.markdown("### ")
col_search, col_region, col_sent = st.columns([3, 1, 1])

search_query = col_search.text_input(
    "Search by institution or title...", placeholder="Search..."
)
region_options = ["All Regions"] + list(result.keys())
selected_region = col_region.selectbox("Region", region_options)
sentiment_options = ["All Sentiment", "bullish", "neutral", "bearish"]
selected_sentiment = col_sent.selectbox("Sentiment", sentiment_options)


def article_matches(article):
    if selected_region != "All Regions" and article.get("region") != selected_region:
        return False
    if selected_sentiment != "All Sentiment" and get_sentiment(article) != selected_sentiment:
        return False
    if search_query:
        haystack = (
            (article.get("title") or "")
            + (article.get("summary") or "")
            + (article.get("why_it_matters") or article.get("whyItMatters") or "")
            + (article.get("source") or "")
        ).lower()
        if search_query.lower() not in haystack:
            return False
    return True


filtered_articles = [a for a in flat_articles if article_matches(a)]

st.markdown(f"### Latest Updates ({len(filtered_articles)} articles)")


if not filtered_articles:
    st.info("No articles match your filters.")
else:
    for art in filtered_articles:
        sentiment = get_sentiment(art)
        badge_color = sentiment_color(sentiment)
        with st.container():
            st.markdown(
                f"""
                <div style="border:1px solid #e2e8f0; border-radius:12px; padding:16px; margin-bottom:12px;">
                    <div style="display:flex; justify-content:space-between; align-items:center;">
                        <div style="font-size:18px; font-weight:700; color:#0f172a;">{art.get('title','')}</div>
                        <span style="background:{badge_color}22; color:{badge_color}; padding:6px 10px; border-radius:12px; font-weight:600; text-transform:capitalize; font-size:12px;">{sentiment}</span>
                    </div>
                    <div style="color:#475569; margin-top:6px;">{art.get('summary','')}</div>
                    <div style="color:#334155; margin-top:10px; font-weight:600;">Why it matters</div>
                    <div style="color:#475569;">{art.get('why_it_matters') or art.get('whyItMatters') or ''}</div>
                    <div style="display:flex; gap:12px; margin-top:12px; flex-wrap:wrap; color:#475569; font-size:13px;">
                        <div>🏦 {art.get('source','')}</div>
                        <div>🌍 {art.get('region','')}</div>
                        <div>📅 {art.get('date','')}</div>
                        {"".join([f"<span style='background:#e2e8f0; padding:4px 8px; border-radius:10px;'>{t}</span>" for t in art.get('tags', [])])}
                    </div>
                    {"<div style='margin-top:10px;'><a href='" + art.get('url','') + "' target='_blank'>Open Article ↗</a></div>" if art.get('url') else ""}
                </div>
                """,
                unsafe_allow_html=True,
            )
